# Generated by Django 5.0 on 2024-05-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testplan",
            name="exact_value",
            field=models.BooleanField(
                default=False,
                help_text="This field indicates that the value returned will be the same as that defined in schema",
                verbose_name="Exact Value",
            ),
        ),
    ]
