# Generated by Django 5.0 on 2024-02-04 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testplans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authenticator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("code", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("code", models.TextField()),
                (
                    "run_automatically",
                    models.BooleanField(
                        default=True,
                        help_text="This field indicates whether this test case can be run automatically.",
                        verbose_name="Can run automatically",
                    ),
                ),
                (
                    "authenticator",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="testcases.authenticator",
                    ),
                ),
                (
                    "testplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="testplans.testplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("r", "Running"),
                            ("p", "Pass"),
                            ("f", "Failure"),
                            ("e", "Error"),
                        ],
                        max_length=1,
                    ),
                ),
                ("message", models.TextField(null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="testcases.testcase",
                    ),
                ),
            ],
        ),
    ]
